#!/usr/bin/env php
<?php

use FC\Resque\Launch\ResqueLauncher;

if(count($argv) <= 1)
{
    die("Usage: $argv[0] {start|stop|restart|status}\n");
}

$cmd = $argv[1];

$configFile = __DIR__ . '/config.local/config.json';

if(count($argv) > 2)
{
    $configFile = $argv[2];
}

include_once __DIR__ . '/vendor/autoload.php';

$starter = new ResqueLauncher($configFile);
switch ($cmd)
{
    case 'start':
        $starter->start();
        break;
    case 'stop':
        $starter->stop();
        break;
    case 'restart':
        $starter->stop();
        $starter->start();
        break;
    case 'status':
        $starter->checkStatus();
        break;
}
